### ISSUE TITLE
convert mars.pb to onnx 

### ISSUE THREAD

**Issue by bhaktiyudha** [John1liu/YOLOV5-DeepSORT-Vehicle-Tracking-Master#5]
Hi, thanks for your work. I need to convert your mars.pb model to onnx file. I am using tf2onnx.convert to convert. I got some error like this
![Screenshot from 2021-11-26 19-52-11](https://user-images.githubusercontent.com/44221675/143584018-8c2ea132-31d5-43b5-b9ef-f5664464e227.png)
can you give me any suggestion about tags ?
Thank you

**Comment by bhaktiyudha** [comment]
my command is like this
`python3 -m tf2onnx.convert --saved-model . --output mars.onnx`

**Comment by John1liu** [comment]
> my command is like this `python3 -m tf2onnx.convert --saved-model . --output mars.onnx`

What is your tag about the --saved-model? I am sorry that I am bussy about another research recent.
